export const orgName = 'otomi'
export const teamNameOwners = 'Owners'
export const teamNameViewer = 'otomi-viewer'
export const otomiValuesRepoName = 'values'
export const otomiChartsRepoName = 'charts'
export const username = 'otomi-admin'
