---
root: true

parserOptions:
  ecmaVersion: 9

extends:
  - eslint:recommended
  - prettier
  - plugin:import/errors
  - plugin:import/warnings

globals:
  cy: true

plugins:
  - import
  - prettier

settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts']

env:
  es6: true
  browser: true
  node: true

rules:
  import/no-extraneous-dependencies: off
  eol-last: ['error', 'always']
  import/extensions: off
  no-shadow: 0
  no-unused-vars: 0
  prefer-destructuring: 0

overrides:
  - files: ['**/*.ts']
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ['./tsconfig.json']
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - prettier/@typescript-eslint
      - plugin:import/typescript
      - plugin:chai-friendly/recommended

    plugins:
      - '@typescript-eslint'

    rules:
      '@typescript-eslint/member-delimiter-style': off
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/no-unused-vars': warn
      import/default: off
