---
root: true

parserOptions:
  project: ['./tsconfig.json']
  ecmaVersion: 2021

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - airbnb-base
  - plugin:prettier/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:chai-friendly/recommended

plugins:
  - import
  - prettier
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: ['.ts']

env:
  es6: true
  mocha: true
  node: true

rules:
  '@typescript-eslint/no-non-null-assertion': off
  import/no-extraneous-dependencies: off
  import/extensions: off
  eol-last: ['error', 'always']
  no-shadow: warn
  no-unused-vars: error
  prefer-destructuring: error
  no-use-before-define: error
  no-console: off
  object-shorthand: error
  no-debugger: error
